### ISSUE TITLE
Disabled Hotgrid Controls

### ISSUE THREAD

**Issue by swashbuck** [cgkineo/adapt-hotgrid#86]
Currently, disabled Hotgrid controls (.hotgrid-popup__controls.is-disabled) are hidden with `visibility: hidden`.

https://github.com/cgkineo/adapt-hotgrid/blob/b80ff075d09170664b43608922e42f0fd3ff8ece/less/hotgridPopup.less#L36

In our project, we wanted the disabled button to be semi-transparent and not hidden entirely.  This requires adding a `visibility: visible` style to override the default.

The problem is that adding this style overrides the .notify__popup's `visibility: hidden` and, as a result, there can be a brief moment where the Back or Next button is visible while the images in the popup load.

What is the reason we're using `visibility: hidden` for the controls?  Could we switch this to something like `opacity: 0.25` and remove the visibility style altogether?  I'm happy to make a PR for this if you'd like.

<img src="https://user-images.githubusercontent.com/898168/177646371-122ecf11-a76c-4580-9d4a-0b391cdf5600.jpg" width="600">
<img src="https://user-images.githubusercontent.com/898168/177646374-d29acc8a-2a33-4ee0-a0e0-cfa0549e0d06.jpg" width="600">

### To recreate:
1. Add this to your Hotgrid styles:
`.hotgrid-popup__controls.is-disabled { visibility: visible; opacity: 0.25;}`
2. Clear the browser cache.
3. Reload the page using bandwidth throttling or use large images (1MB+) in a Hotgrid.

**Comment by swashbuck** [comment]
@kirsty-hames @guywillis

**Comment by kirsty-hames** [comment]
Hey @swashbuck, the use of `visibility:hidden` for disabled controls also applies to [Hotgraphic popup](https://github.com/adaptlearning/adapt-contrib-hotgraphic/blob/2556db53ef5e949583e2192b840f6834aa225906/less/hotgraphicPopup.less#L36) and [Narrative controls](https://github.com/adaptlearning/adapt-contrib-narrative/blob/40250cae0f445ac1915a655b6cd43a60138e9c89/js/NarrativeView.js#L273). 
I could be wrong but I think `visibility` was used instead of `opacity` due to accessibility. You can still tab/focus on an element with `opacity` but not `visibility:hidden`. 
For the popup controls at least, I don't see why we couldn't use `opacity` as the `tabindex="-1" aria-hidden="true" aria-disabled="true"` prevents the element being tabbed/focusable.

**Comment by oliverfoster** [comment]
If you use `opacity` and  `aria-disabled="true"` without ` tabindex="-1" aria-hidden="true" `. Then the button will be focusable, readable (as disabled), knocked back visually and not clickable.

**Comment by swashbuck** [comment]
Thanks, both.  Hotgrid currently uses `Adapt.a11y.toggleAccessibleEnabled` to enable/disable the button.  That calls two functions, `toggleAccessible` and `toggleEnabled`, and both of those set tabindex="-1" when disabling the button.

Would you recommend modifying one or both of these functions, or creating a new function (ex. toggleDisabled) that doesn't contain the tabindex attribute change?

The opacity / visibility CSS change can be made to individual plugins (Hotgrid, Hotgraphic, Narrative).

**Comment by oliverfoster** [comment]
I think we can just remove the tabindex bits from toggleEnabled https://github.com/adaptlearning/adapt-contrib-core/blob/master/js/a11y.js#L303-L307 and use that instead

**Comment by swashbuck** [comment]
I've created a ticket/PR to remove tabindex from toggleEnabled:
https://github.com/adaptlearning/adapt-contrib-core/pull/221

I will create a PR shortly to remove visibility hidden from Hotgrids.
